### PR TITLE
feat: add CLAP support

### PR DESCRIPTION
**Pull request by RustoMCSpit**
Add support for the CLAP format using [clap-juce-extensions](https://github.com/free-audio/clap-juce-extensions).

### CODE REVIEW

**Comment by jerryuhoo** [comment]
Thanks!

**Comment by RustoMCSpit** [comment]
> Thanks!

does this build right for you?

**Comment by RustoMCSpit** [comment]
> Thanks!

btw, you have to add the CLAP extension as a submodule.

**Comment by RustoMCSpit** [comment]
@jerryuhoo  you have to add the CLAP extension as a submodule.

**Comment by jerryuhoo** [comment]
Sorry, I was busy. I have added the submodule but I haven't tested it.

**Pull request merged**
